# DAY 08

In [4]:
import numpy as np 

In [5]:
arr = np.array([1,2,3,4,5,6])
print(arr[3])

4


In [9]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0, 2])

3


In [24]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(arr[2, 1])
print(arr[1, 2])
print(arr[3, 2])
print(arr[0, 0])

8
6
12
1


In [33]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[0:5:2])

[1 3 5]


In [38]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, :2])

[6 7]


In [39]:
# Copy and View 
arr = np.array([1,2,3,4,5,6,7])

x = arr.copy()
arr[0] = 10

print(arr)
print(x)

[10  2  3  4  5  6  7]
[1 2 3 4 5 6 7]


In [40]:
arr = np.array([5,6,7,8,9])

x = arr.view()

arr[1] = 12

print(arr)
print(x)

[ 5 12  7  8  9]
[ 5 12  7  8  9]


In [41]:
arr1 = np.array([2,3,4,5])
arr2 = np.array([6,7,8,9])

arr = np.concatenate((arr1, arr2))

print(arr)

[2 3 4 5 6 7 8 9]
