# DAY 07 - CONTINUATION 

# Numpy - Numpy is a python library which is used for fast numerical and mathematical operations 

In [3]:
import numpy as np

arr = np.array([1,2,3])

print(arr)

[1 2 3]


In [4]:
# 0D
arr = np.array(45) 
arr

array(45)

In [5]:
# 1D 
arr1D = np.array([4, 5, 6])
arr1D

array([4, 5, 6])

In [6]:
# 2D 
arr2D = np.array([[1,2,4], [5,6,9]])
arr2D

array([[1, 2, 4],
       [5, 6, 9]])

In [10]:
arr3D = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
arr3D

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr = [0,1,2,3,4,5,6,7,8,9,10]
for i in arr:
    if i % 2 == 0:
        print("Even Number in the given is:", i)            

Even Number in the given is: 0
Even Number in the given is: 2
Even Number in the given is: 4
Even Number in the given is: 6
Even Number in the given is: 8
Even Number in the given is: 10


In [20]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
for row in arr:
    for num in row:
        if num % 2 == 0:
            print("Even number:", num) 

Even number: 2
Even number: 4
Even number: 6
Even number: 8
Even number: 10
Even number: 12
